---
# tasks file for roles/osp-instance-delete
#  - name: Fetch Instance Info
#  - name: Delete instances

- name: Fetch Instance Info
  os_server_facts:
    cloud: ospcloud
    region_name: RegionOne
  register: osp_servers_result
  tags:
    - cleanup

  - name: Delete instances
    os_server:
      cloud: ospcloud
      name: "{{ item.name }}"
      state: absent
      image: rhel-guest
      flavor: m2.small
      delete_fip: true
    with_items: 
    - "{{ osp_servers_result.ansible_facts.openstack_servers }}"
    tags:
      - cleanup  
   
