#- hosts: tag_instance_filter_three_tier_app_*k.kovacs*
#- hosts: tag_instance_filter_three_tier_app_k.kovacs_redhat_com
- hosts: tag_instance_filter_three_tier_app_k_kovacs_leonardo_com_au
#- hosts: tag_instance_filter_three_tier_app_*kovacs*
  gather_facts: false
  tasks:
  - name: Check the instances status
    wait_for:
      host: "{{ item }}"
      port: 22
      search_regex: OpenSSH
      timeout: 600
    delegate_to: localhost
    with_items:
      - "{{ inventory_hostname }}"

