- hosts: frontends
  gather_facts: false
  tasks:

#  - name: Use Uri module for wrting smoke test.
#  - name: Fail if 'Ansible has done its job' is not in the page content

  - name: Use Uri module for writing smoke test.
    uri:
      url: http://{{ inventory_hostname }}/ansible
      return_content: yes
#      delegate_to: localhost       
    register: webpage

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
    when: "'Ansible has done its job' not in webpage.content"
