- hosts: frontends
  gather_facts: false
  tasks:

#  - name: Use Uri module for wrting smoke test.
#  - name: Fail if 'Ansible has done its job' is not in the page content

- hosts: frontends
  gather_facts: false
  tasks:

  - name: Use Uri module for wrting smoke test.
    uri: 
      url: http://{{ hostvars[groups['frontends'][0]].ansible_host }}
      return_content: yes
    register: webpage  

  - name: Debug 
    debug:  
      var: webpage

  - name: Fail if 'Ansible has done its job' is not in the page content
    fail:
      when: "'Ansible has done its job' not in webpage.results[0].content"
