- hosts: frontends
  gather_facts: false
  tasks:

  - name: Check that a page returns a status 200 and fail if the word is not in the page contents
    uri:
      url: http://{{ hostvars[groups['frontends'][0]].ansible_host }}
      return_content: yes
    register: webpage
    failed_when: "'Ansible has done its job' not in webpage.content"

  - name: Debug 
    debug:  
      var: webpage


