---
# tasks file for base-config

- name: Enable repos
  become: yes
  template:
    src: open_three-tier-app.repo
    dest: /etc/yum.repos.d/open_three-tier-app.repo
    mode: 0644

#- name: Enable repos
#  become: yes
#  get_url:
#    url: http://www.opentlc.com/download/ansible_bootcamp/repo/internal.repo
#    dest: /etc/yum.repos.d/internal.repo
